### PR TITLE
Genbank

### LINKED ISSUE #3: genbank support, stacked contigs, etc.
Hi David,
I really like your genomenotebook project. 
Just wanted to let you know that I've been working on adding a bunch of features to it. The purpose is so that it can be used to compare stacks of genome neighborhoods, for example from metagenomic contigs.

Specifically, I'd like to add support:
- genbank file input
- stacked contigs
   -  For example, with a shared x-axis.
- stacked features within each contig
- custom colors for each annotation
- various improvements to mouseovers
- allow different annotations and names for different feature types
- export to `.html` file
- write names on top of feature glyphs (will make stacked features look better)
    - I think this will be the trickiest part, because of needing to turn on and off names based on zoom level.
- clean up the way that annotations and mouseovers are handled

Probably some other stuff that isn't coming to mind right now. It's looking like most of that stuff can be added without breaking backwards compatibility. I've gotten a good start on it, but still have some work to do. Hopefully some or all of it can be integrated back into the main repo eventually.

My branch is here:
https://github.com/seanrjohnson/genomenotebook/tree/genbank

The diff for a recent commit is here:
https://github.com/seanrjohnson/genomenotebook/commit/ac762887bd4c87e0a14d455199810bd8a38a0381

A jupyter notebook with a demo of some of the stuff is here:
https://github.com/seanrjohnson/genomenotebook/blob/genbank/nbs/03_Stacking.ipynb

I'd be happy to hear your thoughts on any of this,

Sean

### PR DESCRIPTION
**Pull request by dbikard**

### CODE REVIEW

**Comment by dbikard** [comment]
CI seems to fail because of " Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks'
Could you maybe run nbdev_clean or nbdev_prepare and make a new commit? I also saw the change you made for Python 3.11, but it's unclear to me whether this will break compatibility with previous Python versions? It would be good to make sure the package also work for people using older versions.

**Comment by seanrjohnson** [comment]
I'm pretty confident that the 3.11 change I made with `Mapping` won't affect compatibility with any version above at least 3.5, I think probably back to 3.3.

I'll look at the CI issue.

**Comment by dbikard** [comment]
I made substantial changes to enable genbank as input as well as z stacking. @seanrjohnson Can you have a look and see if anything I changed in your code needs to be fixed?

We also still need to improve the docs to highlight the new features as well as test everything thoroughly before we can merge,

**Comment by dbikard** [comment]
I now see that the way you changed how attributes are kept in the patches DataFrame and added to the hover tool mean that it is no longer feasible for the user to easily add data to be displayed when hovering as was shown in the Options notebook "Adding information to be displayed when hovering". The user would now have to modify the GFF file which is not very convenient. I'll try to think about a possible fix.

**Comment by dbikard** [comment]
> I now see that the way you changed how attributes are kept in the patches DataFrame and added to the hover tool mean that it is no longer feasible for the user to easily add data to be displayed when hovering as was shown in the Options notebook "Adding information to be displayed when hovering". The user would now have to modify the GFF file which is not very convenient. I'll try to think about a possible fix.

This is now fixed with a custom function to add data to the tooltip.

**Pull request merged**
